/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Departments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Employees_list"];
        put?: never;
        post: operations["Employees_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Employees_get"];
        put?: never;
        post?: never;
        delete: operations["Employees_remove"];
        options?: never;
        head?: never;
        patch: operations["Employees_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChangedMetaDto: {
            /** @description false when the PATCH matched the stored values after normalization (no write, same version) */
            changed: boolean;
            /** Format: uuid */
            requestId: string;
        };
        CreateEmployeeDto: {
            /**
             * @example engineering
             * @enum {string}
             */
            departmentId: "engineering" | "marketing" | "sales" | "hr";
            /**
             * @description true = Active, false = In Active
             * @example true
             */
            isActive: boolean;
            /**
             * Format: date
             * @example 2026-09-01
             */
            joinDate: string;
            /**
             * @description Trimmed and NFC-normalized; 1–100 code points.
             * @example Dana Lee
             */
            name: string;
            /**
             * @description Decimal string, 0–9999999999.99
             * @example 62000.00
             */
            salary: string;
        };
        DepartmentDto: {
            /** @example engineering */
            id: string;
            /** @example Engineering */
            name: string;
            /** @example 1 */
            sortOrder: number;
        };
        EmployeeDto: {
            /** @enum {string} */
            departmentId: "engineering" | "marketing" | "sales" | "hr";
            /** @example Engineering */
            departmentName: string;
            /** @example 106 */
            id: number;
            /** @example true */
            isActive: boolean;
            /**
             * Format: date
             * @example 2026-09-01
             */
            joinDate: string;
            /**
             * Format: date
             * @example 2026-10-01
             */
            lastUpdatedDate: string;
            /** @example Dana Lee */
            name: string;
            /** @example 62000.00 */
            salary: string;
            /** @example 1 */
            version: number;
        };
        EmployeeListMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            pageSize: number;
            /** Format: uuid */
            requestId: string;
            /** @enum {string} */
            sortBy: "id" | "name" | "department" | "joinDate" | "isActive" | "lastUpdatedDate" | "salary";
            /** @enum {string} */
            sortOrder: "asc" | "desc";
            /** @example 5 */
            total: number;
            /**
             * @description 0 when total is 0
             * @example 1
             */
            totalPages: number;
        };
        ErrorBodyDto: {
            /** @example VALIDATION_ERROR */
            code: string;
            /** @description VERSION_CONFLICT only */
            currentVersion?: number;
            details?: components["schemas"]["FieldErrorDto"][];
            /** @example Please correct the highlighted fields. */
            message: string;
            /** Format: uuid */
            requestId: string;
        };
        ErrorEnvelopeDto: {
            error: components["schemas"]["ErrorBodyDto"];
        };
        FieldErrorDto: {
            /** @example DECIMAL_SCALE_EXCEEDED */
            code: string;
            /** @example salary */
            field: string;
            /** @example Salary must have at most 2 decimal places. */
            message: string;
        };
        MetaDto: {
            /** Format: uuid */
            requestId: string;
        };
        UpdateEmployeeDto: {
            /** @enum {string} */
            departmentId?: "engineering" | "marketing" | "sales" | "hr";
            isActive?: boolean;
            /** Format: date */
            joinDate?: string;
            /** @example Dana Lee */
            name?: string;
            /** @example 63000.00 */
            salary?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Departments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DepartmentDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description RATE_LIMITED */
            429: {
                headers: {
                    /** @description Seconds to wait before retrying */
                    "Retry-After"?: string;
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Employees_list: {
        parameters: {
            query?: {
                /** @description Case-insensitive name contains; trimmed; ≤100 characters */
                q?: string;
                departmentId?: "engineering" | "marketing" | "sales" | "hr";
                status?: "all" | "active" | "inactive";
                page?: number;
                pageSize?: number;
                sortBy?: "id" | "name" | "department" | "joinDate" | "isActive" | "lastUpdatedDate" | "salary";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EmployeeDto"][];
                        meta: components["schemas"]["EmployeeListMetaDto"];
                    };
                };
            };
            /** @description VALIDATION_ERROR / INVALID_QUERY / INVALID_IDEMPOTENCY_KEY / MALFORMED_JSON */
            400: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description RATE_LIMITED */
            429: {
                headers: {
                    /** @description Seconds to wait before retrying */
                    "Retry-After"?: string;
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Employees_create: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID generated once per create intent */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeDto"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    /** @description Quoted employee version, e.g. "1" — send it back as If-Match */
                    ETag?: string;
                    /** @description "true" when the response was replayed for a repeated Idempotency-Key */
                    "Idempotency-Replayed"?: string;
                    /** @description Path of the created resource */
                    Location?: string;
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EmployeeDto"];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description VALIDATION_ERROR / INVALID_QUERY / INVALID_IDEMPOTENCY_KEY / MALFORMED_JSON */
            400: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description VERSION_CONFLICT / IDEMPOTENCY_CONFLICT */
            409: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description PAYLOAD_TOO_LARGE */
            413: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNSUPPORTED_MEDIA_TYPE */
            415: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description RATE_LIMITED */
            429: {
                headers: {
                    /** @description Seconds to wait before retrying */
                    "Retry-After"?: string;
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Employees_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    /** @description Quoted employee version, e.g. "1" — send it back as If-Match */
                    ETag?: string;
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EmployeeDto"];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description EMPLOYEE_NOT_FOUND */
            404: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description RATE_LIMITED */
            429: {
                headers: {
                    /** @description Seconds to wait before retrying */
                    "Retry-After"?: string;
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Employees_remove: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_ERROR / INVALID_QUERY / INVALID_IDEMPOTENCY_KEY / MALFORMED_JSON */
            400: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description EMPLOYEE_NOT_FOUND */
            404: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description VERSION_CONFLICT / IDEMPOTENCY_CONFLICT */
            409: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description PRECONDITION_REQUIRED (If-Match missing) */
            428: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description RATE_LIMITED */
            429: {
                headers: {
                    /** @description Seconds to wait before retrying */
                    "Retry-After"?: string;
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Employees_update: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted employee version, e.g. "1" */
                "If-Match": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeDto"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    /** @description Quoted employee version, e.g. "1" — send it back as If-Match */
                    ETag?: string;
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EmployeeDto"];
                        meta: components["schemas"]["ChangedMetaDto"];
                    };
                };
            };
            /** @description VALIDATION_ERROR / INVALID_QUERY / INVALID_IDEMPOTENCY_KEY / MALFORMED_JSON */
            400: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description EMPLOYEE_NOT_FOUND */
            404: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description VERSION_CONFLICT / IDEMPOTENCY_CONFLICT */
            409: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description PAYLOAD_TOO_LARGE */
            413: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNSUPPORTED_MEDIA_TYPE */
            415: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description PRECONDITION_REQUIRED (If-Match missing) */
            428: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description RATE_LIMITED */
            429: {
                headers: {
                    /** @description Seconds to wait before retrying */
                    "Retry-After"?: string;
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description INTERNAL_ERROR */
            500: {
                headers: {
                    /** @description Server-generated UUID for this request */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
}
