/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Auth_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Auth_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Departments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Employees_list"];
        put?: never;
        post: operations["Employees_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Employees_get"];
        put?: never;
        post?: never;
        delete: operations["Employees_remove"];
        options?: never;
        head?: never;
        patch: operations["Employees_update"];
        trace?: never;
    };
    "/api/v1/integrations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Integrations_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Reports_list"];
        put?: never;
        post: operations["Reports_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/report-jobs/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InternalReports_claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/report-jobs/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InternalReports_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/report-jobs/{id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InternalReports_fail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/reports/scheduled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InternalReports_scheduled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BuildDto: {
            appVersion: string;
            commitSha: string;
        };
        ClaimedReportJobDto: {
            attempt: number;
            /** Format: date-time */
            leaseExpiresAt: string;
            leaseToken: string;
            model: string;
            promptVersion: string;
            /** Format: uuid */
            reportId: string;
            snapshot: components["schemas"]["SnapshotDto"];
        };
        CompleteReportJobDto: {
            /** @enum {string} */
            generatedBy: "GEMINI" | "TEMPLATE";
            leaseToken: string;
            /** @example gemini-3.5-flash-lite */
            model: string | null;
            /**
             * @example {
             *       "bullets": [
             *         "...",
             *         "...",
             *         "..."
             *       ],
             *       "headline": "ภาพรวมพนักงาน"
             *     }
             */
            narrative: Record<string, never>;
            /** @example employee-summary-v1 */
            promptVersion: string;
        };
        CreateEmployeeDto: {
            /**
             * @example engineering
             * @enum {string}
             */
            departmentId: "engineering" | "marketing" | "sales" | "hr";
            /**
             * @description true = Active, false = In Active
             * @example true
             */
            isActive: boolean;
            /**
             * Format: date
             * @example 2026-09-01
             */
            joinDate: string;
            /**
             * @description Trimmed and NFC-normalized; 1–100 code points.
             * @example Dana Lee
             */
            name: string;
            /**
             * @description Decimal string, 0–9999999999.99
             * @example 62000.00
             */
            salary: string;
        };
        CreateReportDto: Record<string, never>;
        DepartmentDto: {
            /** @example engineering */
            id: string;
            /** @example Engineering */
            name: string;
            /** @example 1 */
            sortOrder: number;
        };
        EmployeeDto: {
            /** @enum {string} */
            departmentId: "engineering" | "marketing" | "sales" | "hr";
            /** @example Engineering */
            departmentName: string;
            /** @example 106 */
            id: number;
            /** @example true */
            isActive: boolean;
            /**
             * Format: date
             * @example 2026-09-01
             */
            joinDate: string;
            /**
             * Format: date
             * @example 2026-10-01
             */
            lastUpdatedDate: string;
            /** @example Dana Lee */
            name: string;
            /**
             * @description Present for Admin only; the key is omitted for Viewer.
             * @example 62000.00
             */
            salary?: string;
            /** @example 1 */
            version: number;
        };
        EmptyBodyDto: Record<string, never>;
        FailReportJobDto: {
            /** @enum {string} */
            errorCode: "PROVIDER_TIMEOUT" | "PROVIDER_RATE_LIMIT" | "PROVIDER_UNAVAILABLE" | "INVALID_MODEL_OUTPUT" | "PROVIDER_AUTH_ERROR" | "MODEL_UNAVAILABLE" | "INVALID_SNAPSHOT" | "CONTENT_REJECTED";
            leaseToken: string;
        };
        GoogleStatusDto: {
            configured: boolean;
        };
        IntegrationStatusDto: {
            build: components["schemas"]["BuildDto"];
            google: components["schemas"]["GoogleStatusDto"];
            reports: components["schemas"]["ReportsStatusDto"];
        };
        JobStatusDto: {
            /** Format: uuid */
            reportId: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
        };
        NarrativeDto: {
            bullets: string[];
            headline: string;
        };
        PermissionsDto: {
            canGenerateReports: boolean;
            canViewIntegrations: boolean;
            canViewSalary: boolean;
            canWriteEmployees: boolean;
        };
        ReportDetailDto: {
            attempts: number;
            /** Format: date-time */
            completedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            errorCode: string | null;
            /** @enum {string|null} */
            generatedBy: "GEMINI" | "TEMPLATE" | null;
            /** Format: uuid */
            id: string;
            model: string | null;
            narrative: components["schemas"]["NarrativeDto"] | null;
            promptVersion: string;
            snapshot: components["schemas"]["SnapshotDto"];
            /** Format: date-time */
            snapshotCapturedAt: string;
            /** @enum {string} */
            source: "MANUAL" | "SCHEDULED";
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
            totalEmployees: number;
        };
        ReportSummaryDto: {
            /** Format: date-time */
            completedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            errorCode: string | null;
            /** @enum {string|null} */
            generatedBy: "GEMINI" | "TEMPLATE" | null;
            /** Format: uuid */
            id: string;
            model: string | null;
            promptVersion: string;
            /** Format: date-time */
            snapshotCapturedAt: string;
            /** @enum {string} */
            source: "MANUAL" | "SCHEDULED";
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
            totalEmployees: number;
        };
        ReportsStatusDto: {
            enabled: boolean;
            model: string;
            workerAvailable: boolean;
            /** Format: date-time */
            workerLastSeenAt: string | null;
        };
        SessionDataDto: {
            /** Format: date-time */
            absoluteExpiresAt: string;
            csrfToken: string;
            permissions: components["schemas"]["PermissionsDto"];
            user: components["schemas"]["SessionUserDto"];
        };
        SessionUserDto: {
            displayName: string;
            email: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "ADMIN" | "VIEWER";
        };
        SnapshotDepartmentDto: {
            active: number;
            id: string;
            inactive: number;
            name: string;
            total: number;
        };
        SnapshotDto: {
            activeEmployees: number;
            /** Format: date */
            businessDate: string;
            /** Format: date-time */
            capturedAt: string;
            departments: components["schemas"]["SnapshotDepartmentDto"][];
            inactiveEmployees: number;
            /** @enum {number} */
            schemaVersion: 1;
            /** @enum {string} */
            timezone: "Asia/Bangkok";
            totalEmployees: number;
        };
        UpdateEmployeeDto: {
            /** @enum {string} */
            departmentId?: "engineering" | "marketing" | "sales" | "hr";
            isActive?: boolean;
            /** Format: date */
            joinDate?: string;
            /** @example Dana Lee */
            name?: string;
            /** @example 63000.00 */
            salary?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDataDto"];
                };
            };
        };
    };
    Departments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentDto"][];
                };
            };
        };
    };
    Employees_list: {
        parameters: {
            query?: {
                /** @description Case-insensitive name contains; trimmed; ≤100 characters */
                q?: string;
                departmentId?: "engineering" | "marketing" | "sales" | "hr";
                status?: "all" | "active" | "inactive";
                page?: number;
                pageSize?: number;
                /** @description salary is Admin-only */
                sortBy?: "id" | "name" | "department" | "joinDate" | "isActive" | "lastUpdatedDate" | "salary";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDto"][];
                };
            };
        };
    };
    Employees_create: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
                /** @description UUID generated once per create intent */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDto"];
                };
            };
        };
    };
    Employees_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDto"];
                };
            };
        };
    };
    Employees_remove: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
                "If-Match": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Employees_update: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
                /** @description Quoted employee version, e.g. "1" */
                "If-Match": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDto"];
                };
            };
        };
    };
    Integrations_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatusDto"];
                };
            };
        };
    };
    Reports_list: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummaryDto"][];
                };
            };
        };
    };
    Reports_create: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummaryDto"];
                };
            };
        };
    };
    Reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDetailDto"];
                };
            };
        };
    };
    InternalReports_claim: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimedReportJobDto"];
                };
            };
        };
    };
    InternalReports_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteReportJobDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusDto"];
                };
            };
        };
    };
    InternalReports_fail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FailReportJobDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusDto"];
                };
            };
        };
    };
    InternalReports_scheduled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummaryDto"];
                };
            };
        };
    };
}
