-- Employee Console — initial schema (PRD §9). Hand-edited from `prisma migrate diff`
-- to add what the Prisma schema cannot express: identity column, CHECK constraints,
-- partial unique indexes for the report queue, and the session table layout.

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'VIEWER');
CREATE TYPE "ReportStatus" AS ENUM ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED');
CREATE TYPE "ReportSource" AS ENUM ('MANUAL', 'SCHEDULED');
CREATE TYPE "ReportGenerator" AS ENUM ('GEMINI', 'TEMPLATE');

-- Departments: fixed master list seeded by db:seed (no UI/API to change it).
CREATE TABLE "departments" (
    "id" VARCHAR(20) NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "sort_order" INTEGER NOT NULL,
    CONSTRAINT "departments_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "departments_name_key" ON "departments"("name");

-- Employees: id is an identity column; the seed inserts Excel IDs 101–105 explicitly and then
-- moves the sequence past max(id) so the next server-generated ID is 106 on a fresh fixture.
CREATE TABLE "employees" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "department_id" VARCHAR(20) NOT NULL,
    "salary" DECIMAL(12,2) NOT NULL,
    "join_date" DATE NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "last_updated_date" DATE NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "employees_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "employees_name_check" CHECK (char_length("name") BETWEEN 1 AND 100 AND "name" = btrim("name")),
    CONSTRAINT "employees_salary_check" CHECK ("salary" >= 0),
    CONSTRAINT "employees_join_date_check" CHECK ("join_date" BETWEEN DATE '1900-01-01' AND DATE '2100-12-31'),
    CONSTRAINT "employees_version_check" CHECK ("version" >= 1)
);

CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "google_sub" VARCHAR(255) NOT NULL,
    "email" VARCHAR(320) NOT NULL,
    "display_name" VARCHAR(200) NOT NULL,
    "role" "Role" NOT NULL,
    "is_enabled" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_login_at" TIMESTAMPTZ(3),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "users_email_lowercase_check" CHECK ("email" = lower(btrim("email")))
);
CREATE UNIQUE INDEX "users_google_sub_key" ON "users"("google_sub");
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- express-session store (connect-pg-simple layout: sid / sess / expire).
CREATE TABLE "sessions" (
    "sid" VARCHAR NOT NULL COLLATE "default",
    "sess" JSON NOT NULL,
    "expire" TIMESTAMP(6) NOT NULL,
    CONSTRAINT "sessions_pkey" PRIMARY KEY ("sid")
);
CREATE INDEX "sessions_expire_idx" ON "sessions"("expire");

-- Reports double as a small durable job queue (PRD §12.3).
CREATE TABLE "reports" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "status" "ReportStatus" NOT NULL,
    "snapshot" JSONB NOT NULL,
    "narrative" JSONB,
    "requested_by" UUID,
    "source" "ReportSource" NOT NULL,
    "generation_date" DATE NOT NULL,
    "prompt_version" VARCHAR(50) NOT NULL,
    "model" VARCHAR(100) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ(3),
    "deadline_at" TIMESTAMPTZ(3) NOT NULL,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "next_attempt_at" TIMESTAMPTZ(3) NOT NULL,
    "lease_token_hash" VARCHAR(64),
    "lease_expires_at" TIMESTAMPTZ(3),
    "error_code" VARCHAR(50),
    "generated_by" "ReportGenerator",
    "result_hash" VARCHAR(64),
    CONSTRAINT "reports_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "reports_attempts_check" CHECK ("attempts" BETWEEN 0 AND 10),
    CONSTRAINT "reports_succeeded_has_narrative_check" CHECK ("status" <> 'SUCCEEDED' OR ("narrative" IS NOT NULL AND "generated_by" IS NOT NULL)),
    CONSTRAINT "reports_running_has_lease_check" CHECK ("status" <> 'RUNNING' OR ("lease_token_hash" IS NOT NULL AND "lease_expires_at" IS NOT NULL))
);
CREATE INDEX "reports_created_at_id_idx" ON "reports"("created_at" DESC, "id" DESC);
CREATE INDEX "reports_status_next_attempt_at_idx" ON "reports"("status", "next_attempt_at");
-- At most one QUEUED/RUNNING report system-wide.
CREATE UNIQUE INDEX "reports_one_active_idx" ON "reports" ((true)) WHERE "status" IN ('QUEUED', 'RUNNING');
-- At most one scheduled report per Bangkok business day.
CREATE UNIQUE INDEX "reports_scheduled_day_idx" ON "reports" ("generation_date") WHERE "source" = 'SCHEDULED';

CREATE TABLE "idempotency_keys" (
    "id" BIGSERIAL NOT NULL,
    "scope" VARCHAR(50) NOT NULL,
    "key" UUID NOT NULL,
    "actor_id" UUID NOT NULL,
    "request_hash" VARCHAR(64) NOT NULL,
    "response_status" INTEGER,
    "response_body" JSONB,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "idempotency_keys_expires_at_idx" ON "idempotency_keys"("expires_at");
CREATE UNIQUE INDEX "idempotency_keys_scope_actor_id_key_key" ON "idempotency_keys"("scope", "actor_id", "key");

CREATE TABLE "integration_state" (
    "key" VARCHAR(50) NOT NULL,
    "last_worker_seen_at" TIMESTAMPTZ(3),
    "flags" JSONB NOT NULL DEFAULT '{}',
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "integration_state_pkey" PRIMARY KEY ("key")
);

-- Database purpose marker (demo/test/performance) checked by reset/fixture/perf commands.
CREATE TABLE "app_meta" (
    "key" VARCHAR(50) NOT NULL,
    "value" VARCHAR(200) NOT NULL,
    CONSTRAINT "app_meta_pkey" PRIMARY KEY ("key")
);

-- AddForeignKey
ALTER TABLE "employees" ADD CONSTRAINT "employees_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "reports" ADD CONSTRAINT "reports_requested_by_fkey" FOREIGN KEY ("requested_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
